#!/bin/bash
#SBATCH --account=rrg-hngharti
#SBATCH -N 1   # node count
#SBATCH --ntasks-per-node=40
#SBATCH -t 01:00:00

# load appropriate compiler
source ~/.login

cd $SLURM_SUBMIT_DIR
# problems with mpiexec/mpirun so use srun
./bin/pspecfemx ./input/vfault_nsplit_serial.sem  -ksp_monitor -ksp_type fgmres -pc_type asm -ksp_gmres_restart 300
